services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000/api}
    restart: unless-stopped
    networks:
      - attendansee-network

networks:
  attendansee-network:
    driver: bridge
