services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://172.25.71.47:8000/api
    # Allow container to access Windows host network
    network_mode: "bridge"
    restart: unless-stopped
