# Generated by Django 5.2.7 on 2025-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecrop',
            name='crop_image_path',
            field=models.ImageField(max_length=500, upload_to='face_crops/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_image_path',
            field=models.ImageField(max_length=500, upload_to='session_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='processed_image_path',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='processed_images/'),
        ),
    ]
