# Generated by Django 5.2.7 on 2025-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_enable_pgvector_add_embedding_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facecrop',
            new_name='face_crops_embeddi_7d6724_idx',
            old_name='face_crops_embeddi_idx',
        ),
        migrations.AlterField(
            model_name='image',
            name='processed_image_path',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to='processed_images/'),
        ),
    ]
