# Generated by Django 5.2.8 on 2026-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_manualattendance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='manualattendance',
            new_name='manual_atte_student_22754a_idx',
            old_name='manual_atte_student_6c4a5f_idx',
        ),
        migrations.RenameIndex(
            model_name='manualattendance',
            new_name='manual_atte_session_7256e2_idx',
            old_name='manual_atte_session_3a8f21_idx',
        ),
        migrations.RenameIndex(
            model_name='manualattendance',
            new_name='manual_atte_is_pres_78ec13_idx',
            old_name='manual_atte_is_pres_d52b89_idx',
        ),
        migrations.AddField(
            model_name='class',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes or additional information about the class'),
        ),
        migrations.AlterField(
            model_name='facecrop',
            name='embedding_model',
            field=models.CharField(blank=True, choices=[('arcface', 'ArcFace (512D)'), ('facenet512', 'FaceNet512 (512D)')], help_text='Model used to generate the embedding', max_length=20, null=True),
        ),
    ]
